#!/bin/sh
# Copyright © 2026 Gornskew Enterprises
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.  Distributed WITHOUT
# ANY WARRANTY; see <https://www.gnu.org/licenses/agpl-3.0.html>.

# Generate .env file for docker-compose

set -e

echo "Generating .env file for docker-compose..."

USER_HOME="${USER_HOME:-$HOME}"

HOST_USER_UID=$(id -u)
DOCKER_GROUP_ID=$(getent group docker 2>/dev/null | cut -d: -f3 || echo 999)
# Honor a pre-set CURRENT_BRANCH (e.g. exported by compose-dev standalone
# bootstrap, which knows which image branch supplied this script); otherwise
# detect from git, falling back to master.
CURRENT_BRANCH="${CURRENT_BRANCH:-$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo master)}"
PROJECTS_DIR="${PROJECTS_DIR:-$USER_HOME/projects}"

# Per-host image variant pin (lite/default/tui/gui/full).  Precedence:
# pre-set env (e.g. from a stack repo's systemd unit Environment= line,
# or a compose-dev --lite/--default/... switch) > existing .env pin
# (so regeneration never silently un-pins a host) > unset (compose
# falls back to full).
if [ -z "${EMACS_IMAGE_VARIANT:-}" ] && [ -f .env ]; then
    EMACS_IMAGE_VARIANT="$(sed -n 's/^EMACS_IMAGE_VARIANT=//p' .env | head -1)"
fi
EMACS_VARIANT_LINE=""
if [ -n "${EMACS_IMAGE_VARIANT:-}" ]; then
    EMACS_VARIANT_LINE="EMACS_IMAGE_VARIANT=$EMACS_IMAGE_VARIANT"
    echo "Pinning skewed-emacs image variant: $EMACS_IMAGE_VARIANT"
fi

# Detect host timezone (best-effort across Linux and macOS)
HOST_TZ=$(
    timedatectl show -p Timezone --value 2>/dev/null || \
    cat /etc/timezone 2>/dev/null || \
    systemsetup -gettimezone 2>/dev/null | awk '{print $NF}' || \
    echo "Etc/UTC"
)

# Optional: mount ~/.emacs-local if it exists
EMACS_LOCAL_LINE=""
if [ -f "$USER_HOME/.emacs-local" ]; then
    EMACS_LOCAL_LINE="EMACS_LOCAL_SRC=$USER_HOME"
fi

cat > .env << EOF
# Docker Compose Environment Variables
# Generated by ./generate-env.sh

# User paths
USER_HOME=$USER_HOME
PROJECTS_DIR=$PROJECTS_DIR

# User/Group IDs
HOST_USER_UID=$HOST_USER_UID
DOCKER_GROUP_ID=$DOCKER_GROUP_ID

# Image and Container names
CURRENT_BRANCH=$CURRENT_BRANCH
EMACS_IMAGE_BRANCH=$CURRENT_BRANCH
EMACS_IMAGE_BASE=skewed-emacs
$EMACS_VARIANT_LINE
GENDL_IMAGE_BRANCH=$CURRENT_BRANCH
GENDL_IMAGE_BASE=gendl

# Network name
DOCKER_NETWORK_NAME=skewed-network
TERM=xterm-256color
COLORTERM=truecolor

$EMACS_LOCAL_LINE

# Timezone (detected from host)
TZ=$HOST_TZ

EOF

echo ""
echo ".env file has the following settings:"
echo "CURRENT_BRANCH: $CURRENT_BRANCH"
echo "PROJECTS_DIR:   $PROJECTS_DIR"
echo "HOST_USER_UID:  $HOST_USER_UID"
echo ""
