#!/bin/zsh
# Copyright © 2026 Gornskew Enterprises
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.  Distributed WITHOUT
# ANY WARRANTY; see <https://www.gnu.org/licenses/agpl-3.0.html>.


ZSH_DISABLE_COMPFIX=true

. $HOME/.bash_profile

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/dcooper8/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
